import React from 'react';
import { prisma } from '@/lib/prisma';
import { notFound } from 'next/navigation';

interface Props {
    params: Promise<{ ticketId: string }>;
}

export default async function TranscriptPage({ params }: Props) {
    const { ticketId } = await params;

    // Fetch ticket with transcript
    // We cast to any because the schema update might not be applied in the client yet due to file locks
    // @ts-ignore
    const ticket = await prisma.ticket.findUnique({
        where: { id: parseInt(ticketId) },
        include: {
            guild: { select: { name: true, icon: true } },
            category: { select: { name: true } }
        }
    }) as any;

    if (!ticket || !ticket.transcript) {
        return notFound();
    }

    return (
        <div className="min-h-screen bg-[#181A20] flex flex-col items-center py-10">
            <div className="w-full max-w-4xl bg-white text-black p-8 rounded-xl shadow-2xl">
                <div className="flex items-center justify-between border-b pb-4 mb-6">
                    <div className="flex items-center gap-4">
                        {ticket.guild?.icon && (
                            <img src={ticket.guild.icon} alt="Guild Icon" className="w-12 h-12 rounded-full" />
                        )}
                        <div>
                            <h1 className="text-2xl font-bold">{ticket.guild?.name || 'Server'} Support Ticket</h1>
                            <p className="text-gray-500">
                                {ticket.category?.name} • Ticket #{ticket.id} • Closed on {ticket.closedAt ? new Date(ticket.closedAt).toLocaleDateString() : 'N/A'}
                            </p>
                        </div>
                    </div>
                </div>

                <div
                    className="prose max-w-none"
                    dangerouslySetInnerHTML={{ __html: ticket.transcript }}
                />
            </div>

            <div className="mt-8 text-gray-500 text-sm">
                Generated by Overlord Bot
            </div>
        </div>
    );
}
